<%@ Page Title="" Language="C#" MasterPageFile="~/Front/Home.master" AutoEventWireup="true" CodeFile="TermandCondition.aspx.cs" Inherits="FaduPrice.Pages.TermandCondition" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">



    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        body {
            background-color: #f1f3f6;
        }

        .terms-box {
            background: #ffffff;
            padding: 30px;
            margin: 30px auto;
            border-radius: 6px;
        }

            .terms-box h1 {
                font-size: 26px;
                font-weight: 600;
                margin-bottom: 20px;
            }

            .terms-box h4 {
                font-size: 18px;
                font-weight: 600;
                margin-top: 30px;
            }

            .terms-box p, .terms-box li {
                font-size: 14px;
                color: #333;
                line-height: 1.7;
            }
    </style>


    <div class="container">
        <div class="terms-box shadow-sm">

            <h1>My Needify Terms of Use</h1>

            <p>
                This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>

            <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name (“Website”), including the related mobile site and mobile application (hereinafter referred to as the “Platform”).
            </p>

            <p>
                The Platform is owned by <strong>My Needify Internet Private Limited</strong>, a company incorporated under the Companies Act, 1956 with its registered office in India (hereinafter referred to as “My Needify”).
            </p>

            <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.
By mere use of the Platform, You shall be contracting with My Needify Internet Private Limited and these terms and conditions constitute Your binding obligations with My Needify.
            </p>

            <p>
                For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform.
The terms "We", "Us", "Our" shall mean My Needify Internet Private Limited.
            </p>

            <p class="fw-bold text-uppercase">
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
            </p>

            <h4>Membership Eligibility</h4>
            <p>
                Transaction on the Platform is available only to persons who can form legally binding contracts under the Indian Contract Act, 1872.
Minors under the age of 18 years may use the Platform only under the supervision of a parent or legal guardian.
            </p>

            <p>
                My Needify reserves the right to terminate your access if it is discovered that you are under the age of 18 years and transacting independently.
            </p>

            <h4>Your Account and Registration Obligations</h4>
            <p>
                You shall be responsible for maintaining the confidentiality of your account credentials and for all activities under your account.
If any information provided is inaccurate or incomplete, My Needify reserves the right to suspend or terminate your account.
            </p>

            <p>
                Your mobile number and email address shall be treated as your primary identifiers on the Platform.
            </p>

            <p>
                My Needify shall not be liable for any loss arising from unauthorized use of your account.
            </p>

            <h4>Communications</h4>
            <p>
                When you use the Platform or communicate with us, you consent to receive communications electronically from My Needify.
            </p>

            <h4>Platform for Transaction and Communication</h4>
            <p>
                The Platform enables buyers and sellers to transact. My Needify is not a party to or controller of transactions between users.
            </p>

            <ul>
                <li>All commercial terms are agreed between buyers and sellers.</li>
                <li>My Needify does not guarantee quality, pricing, or availability.</li>
                <li>My Needify is not responsible for non-performance by sellers.</li>
                <li>Any disputes must be resolved between buyer and seller.</li>
            </ul>

            <p>
                My Needify does not take ownership or possession of any products sold on the Platform.
            </p>

            <h4>GST & Business Purchases</h4>
            <p>
                Certain products may be eligible for business purchases. GST invoices will be issued by sellers where applicable.
My Needify does not verify GSTIN details provided by users.
            </p>

            <p>
                You shall be solely responsible for compliance with GST laws and indemnify My Needify against any claims.
            </p>

            <h4>Charges</h4>
            <p>
                My Needify may charge fees for services provided on the Platform and reserves the right to modify such fees at any time.
All charges shall be displayed on the Platform and quoted in Indian Rupees.
            </p>

            <p class="mt-4">
                By continuing to use the Platform, you acknowledge that you have read, understood, and agreed to these Terms of Use.
            </p>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

</asp:Content>
