//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSBillingMaster.Pages
{
    public partial class Hire
    {

    }
}
